import Link from "next/link";
import { requireAdmin } from "@/server/auth/admin-auth";
import { journalCategories, listJournal, type JournalCategory } from "@/server/security/audit-journal";
import { Select } from "@/components/ui/fields/Select";
import s from "@/components/workspace/workspace.module.css";

export const metadata = { title: "Журнал событий · Admin" };
const categoryLabels: Record<JournalCategory, string> = { BRIEFS: "Заявки", PROJECTS: "Проекты", CLIENTS: "Клиенты", PAYMENTS: "Оплаты", MATERIALS: "Материалы", NOTIFICATIONS: "Уведомления", PRIVACY: "Персональные данные", SYSTEM: "Система" };
const eventLabels: Record<string, string> = { BRIEF_CREATED: "Заявка поступила", BRIEF_UPDATED: "Заявка обновлена", BRIEF_STATUS_CHANGED: "Статус заявки изменён", BRIEF_PROJECT_CREATED: "Заявка принята в работу", CLIENT_CREATED: "Клиент создан", CLIENT_DEACTIVATED: "Клиент деактивирован", CLIENT_REACTIVATED: "Клиент активирован", PROJECT_CREATED: "Проект создан", PROJECT_UPDATED: "Проект изменён", PROJECT_ARCHIVED: "Проект архивирован", PROJECT_RESTORED: "Проект восстановлен", STAGE_CREATED: "Этап создан", STAGE_UPDATED: "Этап изменён", STAGE_ARCHIVED: "Этап архивирован", RESULT_PUBLISHED: "Результат опубликован", ACCEPTED: "Этап принят клиентом", CHANGES: "Клиент запросил правки", ROUND_CLASSIFIED: "Раунд правок классифицирован", PAYMENT_UPDATED: "Платёж обновлён", MATERIAL_ADDED: "Материал добавлен", NOTIFICATION_ENQUEUED: "Уведомление поставлено в очередь", PRIVACY_REQUEST_REGISTERED: "Запрос субъекта зарегистрирован", PRIVACY_REQUEST_PREPARED: "Область запроса подтверждена", PRIVACY_REQUEST_COMPLETED: "Обработка прекращена, данные уничтожены" };

export default async function EventsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  await requireAdmin(); const query = await searchParams;
  const category = journalCategories.includes(query.category as JournalCategory) ? query.category as JournalCategory : undefined;
  const from = query.from && /^\d{4}-\d{2}-\d{2}$/.test(query.from) ? new Date(`${query.from}T00:00:00Z`) : undefined;
  const to = query.to && /^\d{4}-\d{2}-\d{2}$/.test(query.to) ? new Date(`${query.to}T23:59:59.999Z`) : undefined;
  const result = await listJournal({ page: Number(query.page) || 1, category, from, to, entityType: query.entityType || undefined, eventType: query.eventType || undefined }, { side: "ADMIN" });
  const pageHref = (page: number) => `/admin/events?${new URLSearchParams(Object.entries({ ...query, page: String(page) }).filter((entry): entry is [string, string] => Boolean(entry[1]))).toString()}`;
  return <div className={`${s.main} ${s.embedded} ${s.stack}`}><div className={s.intro}><h1>Журнал событий</h1><p className={s.muted}>Бизнес-хронология проектов и юридический audit trail показаны вместе, но помечены разными источниками. Записи доступны только администраторам и не редактируются через приложение.</p></div><section className={s.panel}><form method="get" className={s.form}><div className={s.grid}><label>Категория<Select name="category" defaultValue={category ?? ""}><option value="">Все категории</option>{journalCategories.map(item => <option value={item} key={item}>{categoryLabels[item]}</option>)}</Select></label><label>Тип сущности<input name="entityType" defaultValue={query.entityType ?? ""} placeholder="PROJECT" maxLength={80} /></label><label>Тип события<input name="eventType" defaultValue={query.eventType ?? ""} placeholder="PROJECT_ARCHIVED" maxLength={100} /></label><label>С даты<input name="from" type="date" defaultValue={query.from ?? ""} /></label><label>По дату<input name="to" type="date" defaultValue={query.to ?? ""} /></label></div><button className={s.primary}>Применить фильтры</button></form></section><section className={`${s.panel} ${s.stack}`}><div className={s.row}><h2>События</h2><span className={s.badge}>{result.total}</span></div>{result.items.length ? <div className={s.history}>{result.items.map(item => <article key={`${item.source}-${item.id}`}><div className={s.row}><strong>{eventLabels[item.eventType] ?? item.eventType}</strong><span className={s.badge}>{categoryLabels[item.category]}</span></div><p className={s.muted}>{item.createdAt.toLocaleString("ru-RU")} · {item.source === "AUDIT" ? "Audit trail" : "Бизнес-хронология"} · {item.entityType}</p>{item.metadata && <p className={s.muted}>{Object.entries(item.metadata).map(([key, value]) => `${key}: ${String(value)}`).join(" · ")}</p>}</article>)}</div> : <p className={s.muted}>По выбранным фильтрам событий нет.</p>}<nav className={s.row} aria-label="Страницы журнала"><span className={s.muted}>Страница {result.page} из {result.pages}</span><div className={s.inlineActions}>{result.page > 1 && <Link href={pageHref(result.page - 1)}>← Назад</Link>}{result.page < result.pages && <Link href={pageHref(result.page + 1)}>Далее →</Link>}</div></nav></section></div>;
}
