import Link from "next/link";
import { requireAdmin } from "@/server/auth/admin-auth";
import { prisma } from "@/server/db/prisma";
import { previewTarget, privacyCategories, type PrivacyCategory } from "@/server/privacy/requests";
import { executeRequest, prepareRequest, registerRequest } from "@/app/admin/privacy/actions";
import { WorkspaceForm } from "@/components/workspace/forms";
import { Select } from "@/components/ui/fields/Select";
import s from "@/components/workspace/workspace.module.css";

export const metadata = { title: "Запросы о персональных данных · Admin" };

const scopeLabels = { BRIEF: "Отдельная заявка", PROJECT: "Отдельный проект", CLIENT: "Клиентский аккаунт" } as const;
const kindLabels = { CONSENT_WITHDRAWAL: "Отзыв согласия", ERASURE: "Требование об уничтожении", PROCESSING_TERMINATION: "Требование прекратить обработку", OTHER: "Иное требование" } as const;
const statusLabels = { REGISTERED: "Зарегистрирован", READY: "Готов к исполнению", COMPLETED: "Исполнен", COMPLETED_WITH_WARNINGS: "Исполнен, есть техническое предупреждение", REJECTED: "Отклонён" } as const;
const categoryLabels: Record<PrivacyCategory, string> = { ACCOUNT: "Аккаунт и контакты", BRIEF: "Заявки", PROJECTS: "Проекты, этапы, решения и платежи", FILES: "Материалы и физические файлы", NOTIFICATIONS: "Уведомления", HISTORY: "События и служебная история" };
const bytes = (value: number) => new Intl.NumberFormat("ru-RU", { style: "unit", unit: value >= 1024 ** 2 ? "megabyte" : "kilobyte", maximumFractionDigits: 1 }).format(value / (value >= 1024 ** 2 ? 1024 ** 2 : 1024));

export default async function PrivacyRequestsPage({ searchParams }: { searchParams: Promise<{ scope?: string }> }) {
  await requireAdmin();
  const query = await searchParams;
  const scope = query.scope === "BRIEF" || query.scope === "PROJECT" ? query.scope : "CLIENT";
  const [clients, projects, briefs, requests] = await Promise.all([
    prisma.clientUser.findMany({ select: { id: true, name: true, username: true }, orderBy: { createdAt: "desc" } }),
    prisma.clientProject.findMany({ select: { id: true, title: true, client: { select: { name: true } } }, orderBy: { updatedAt: "desc" } }),
    prisma.briefRequest.findMany({ select: { id: true, number: true, name: true }, orderBy: { createdAt: "desc" } }),
    prisma.personalDataRequest.findMany({ orderBy: { createdAt: "desc" }, take: 100 }),
  ]);
  const targets = scope === "CLIENT" ? clients.map(item => ({ id: item.id, label: `${item.name} · ${item.username}` })) : scope === "PROJECT" ? projects.map(item => ({ id: item.id, label: `${item.title} · ${item.client.name}` })) : briefs.map(item => ({ id: item.id, label: `№ ${item.number} · ${item.name}` }));
  const active = await Promise.all(requests.filter(item => item.targetId && (item.status === "REGISTERED" || item.status === "READY")).map(async item => ({ request: item, preview: await previewTarget(item.scope, item.targetId!) })));

  return <div className={`${s.main} ${s.embedded} ${s.stack}`}>
    <div className={s.intro}><h1>Прекращение обработки персональных данных</h1><p className={s.muted}>Отдельный процесс для запросов субъекта. Он не меняет обычный порядок «завершение → архив → очистка по сроку».</p></div>
    <section className={`${s.panel} ${s.stack}`}><div><h2>Зарегистрировать запрос</h2><p className={s.muted}>Сначала зафиксируйте дату и область. Уничтожение на этом шаге не запускается.</p></div><nav className={s.projectFilters} aria-label="Область запроса">{Object.entries(scopeLabels).map(([value, label]) => <Link key={value} className={`${s.projectFilter} ${scope === value ? s.projectFilterActive : ""}`} href={`/admin/privacy-requests?scope=${value}`}>{label}</Link>)}</nav>{targets.length ? <WorkspaceForm action={registerRequest} submit="Зарегистрировать без удаления"><input type="hidden" name="scope" value={scope} /><label>Тип требования<Select name="kind" defaultValue="CONSENT_WITHDRAWAL">{Object.entries(kindLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</Select></label><label>Субъект и область<Select name="targetId" required>{targets.map(target => <option value={target.id} key={target.id}>{target.label}</option>)}</Select></label><div className={s.grid}><label>Дата получения<input name="receivedAt" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><label>Контрольный срок · необязательно<input name="dueAt" type="date" /></label></div></WorkspaceForm> : <p className={s.muted}>Для выбранной области нет доступных объектов.</p>}</section>
    {active.map(({ request, preview }) => <section className={`${s.panel} ${s.stack}`} key={request.id}><div className={s.row}><div><h2>Запрос № {request.number} · {kindLabels[request.kind]}</h2><p className={s.muted}>{scopeLabels[request.scope]} · получен {request.receivedAt.toLocaleDateString("ru-RU")}{request.dueAt ? ` · срок ${request.dueAt.toLocaleDateString("ru-RU")}` : ""}</p></div><span className={s.badge}>{statusLabels[request.status]}</span></div>{preview.targetExists ? <><div className={s.destructiveWarning}><strong>{preview.label}</strong><p>Заявок: {preview.counts.briefs} · проектов: {preview.counts.projects} · материалов: {preview.counts.materials} · файлов: {preview.counts.files} ({bytes(preview.counts.bytes)}) · уведомлений: {preview.counts.notifications} · событий: {preview.counts.events}</p></div>{request.status === "REGISTERED" ? <WorkspaceForm action={prepareRequest.bind(null, request.id)} submit="Подтвердить область и исключения" tone="danger"><fieldset><legend>Сохранить по иному законному основанию / исключению</legend><p className={s.muted}>Ничего не отмечайте, если вся рассчитанная область подлежит уничтожению. Несовместимые зависимости сервер заблокирует.</p><div className={s.cleanupList}>{privacyCategories.map(category => <label className={s.cleanupItem} key={category}><input type="checkbox" name="excludedCategory" value={category} /><span><strong>{categoryLabels[category]}</strong><small>Эта категория не будет уничтожена</small></span></label>)}</div></fieldset><label>Основание сохранения категории<textarea name="exclusionReason" maxLength={1000} placeholder="Только правовое основание или исключение — без ФИО, email и содержания проекта" /></label><label className={s.checkbox}><input type="checkbox" name="reviewed" value="yes" required />Я проверил состав, принадлежность и последствия удаления</label></WorkspaceForm> : <WorkspaceForm action={executeRequest.bind(null, request.id)} submit="Необратимо исполнить запрос" tone="danger"><p>Первое подтверждение получено. Сервер повторно рассчитает область и остановит операцию при нарушении изоляции.</p><label className={s.checkbox}><input type="checkbox" name="finalConfirm" value="yes" required />Подтверждаю необратимое уничтожение данных и физических файлов</label><label>Введите «УДАЛИТЬ {request.number}»<input name="confirmation" required autoComplete="off" pattern={`УДАЛИТЬ ${request.number}`} /></label></WorkspaceForm>}</> : <p className={s.error}>Целевой объект больше не существует. Исполнение заблокировано.</p>}</section>)}
    <section className={`${s.panel} ${s.stack}`}><div><h2>Обезличенный журнал исполнения</h2><p className={s.muted}>После исполнения здесь нет ФИО, email, исходного идентификатора или содержания проекта.</p></div>{requests.filter(item => item.completedAt).length ? <div className={s.cleanupList}>{requests.filter(item => item.completedAt).map(item => <div className={s.cleanupItem} key={item.id}><span><strong>Запрос № {item.number} · {kindLabels[item.kind]}</strong><small>Получен {item.receivedAt.toLocaleDateString("ru-RU")} · исполнен {item.completedAt!.toLocaleDateString("ru-RU")} · {statusLabels[item.status]}{item.storageWarnings ? ` · файлов в карантине: ${item.storageWarnings}` : ""}</small><small>{Array.isArray(item.destroyedCategories) ? item.destroyedCategories.join("; ") : "Категории не указаны"}</small></span></div>)}</div> : <p className={s.muted}>Исполненных запросов пока нет.</p>}</section>
  </div>;
}
