
import { Select } from "@/components/ui/fields/Select";
import Link from "next/link";
import { prisma } from "@/server/db/prisma";
import { requireAdmin } from "@/server/auth/admin-auth";
import { createClient, createProject } from "@/app/client/actions";
import { WorkspaceForm } from "@/components/workspace/forms";
import { statuses } from "@/server/client/model";
import s from "@/components/workspace/workspace.module.css";
import type { Prisma } from "@/generated/prisma/client";
export default async function AdminProjects({ searchParams }: { searchParams: Promise<{ view?: string }> }) {
  await requireAdmin();
  const view = (await searchParams).view ?? "active";
  const where: Prisma.ClientProjectWhereInput = view === "archive" ? { archivedAt: { not: null } } : view === "completed" ? { archivedAt: null, status: { in: ["COMPLETED", "WARRANTY"] } } : view === "all" ? { archivedAt: null } : { archivedAt: null, status: { notIn: ["COMPLETED", "WARRANTY"] } };
  const [clients, projects, allCount, activeCount, completedCount, archiveCount] = await Promise.all([prisma.clientUser.findMany({ where: { active: true }, select: { id: true, name: true, username: true }, orderBy: { name: "asc" } }), prisma.clientProject.findMany({ where, include: { client: { select: { name: true } } }, orderBy: { updatedAt: "desc" } }), prisma.clientProject.count({ where: { archivedAt: null } }), prisma.clientProject.count({ where: { archivedAt: null, status: { notIn: ["COMPLETED", "WARRANTY"] } } }), prisma.clientProject.count({ where: { archivedAt: null, status: { in: ["COMPLETED", "WARRANTY"] } } }), prisma.clientProject.count({ where: { archivedAt: { not: null } } })]);
  const archived = view === "archive";
  return <div className={`${s.main} ${s.embedded} ${s.stack}`}><div className={s.intro}><h1>Проекты клиентов</h1><p className={s.muted}>Архив не отображается в основном рабочем списке.</p></div><nav className={s.projectFilters} aria-label="Состояние проектов"><Link className={`${s.projectFilter} ${view === "all" ? s.projectFilterActive : ""}`} href="/admin/projects?view=all">Все: {allCount}</Link><Link className={`${s.projectFilter} ${view === "active" ? s.projectFilterActive : ""}`} href="/admin/projects">Активные: {activeCount}</Link><Link className={`${s.projectFilter} ${view === "completed" ? s.projectFilterActive : ""}`} href="/admin/projects?view=completed">Завершённые: {completedCount}</Link><Link className={`${s.projectFilter} ${archived ? s.projectFilterActive : ""}`} href="/admin/projects?view=archive">В архиве: {archiveCount}</Link></nav><div className={s.stack}>{projects.length ? projects.map(project => <article key={project.id} className={`${s.panel} ${s.row}`}><div><h2><Link href={`/admin/projects/${project.id}`}>{project.title}</Link></h2><p className={s.muted}>{project.client.name}{project.archivedAt ? ` · В архиве с ${project.archivedAt.toLocaleDateString("ru-RU")}` : ""}{project.deleteAfter ? ` · Кандидат на очистку после ${project.deleteAfter.toLocaleDateString("ru-RU")}` : ""}</p></div><span className={s.badge}>{project.archivedAt ? "В архиве" : statuses[project.status]}</span></article>) : <p className={s.panel}>{archived ? "Архив проектов пуст." : "В этой группе проектов нет."}</p>}</div>{!archived && <div className={s.grid}><section className={s.panel}><h2>Новый клиент</h2><WorkspaceForm action={createClient} submit="Создать аккаунт"><label>Имя клиента<input name="name" required maxLength={200} /></label><label>Логин<input name="username" required minLength={3} maxLength={100} autoComplete="off" pattern="[a-zA-Z0-9._@+\-]{3,100}" /></label><label>E-mail · необязательно<input name="email" type="email" maxLength={320} autoComplete="email" /></label><label>Пароль · от 12 символов<input name="password" type="password" required minLength={12} maxLength={200} autoComplete="new-password" /></label><p className={s.muted}>Email-уведомления клиент включает самостоятельно.</p></WorkspaceForm></section><section className={s.panel}><h2>Новый проект</h2>{clients.length ? <WorkspaceForm action={createProject} submit="Создать проект"><label>Клиент<Select name="clientId" required>{clients.map(client => <option key={client.id} value={client.id}>{client.name} · {client.username}</option>)}</Select></label><label>Название<input name="title" required maxLength={200} /></label><label>Описание<textarea name="description" maxLength={10000} /></label></WorkspaceForm> : <p className={s.muted}>Сначала создайте клиентский аккаунт.</p>}</section></div>}</div>;
}
