import { createHash, randomUUID } from "node:crypto";
import { spawn } from "node:child_process";
import { constants, createReadStream, createWriteStream } from "node:fs";
import { access, chmod, lstat, mkdir, readFile, readdir, rename, rm, stat, writeFile } from "node:fs/promises";
import { join, resolve, sep } from "node:path";
import { pipeline } from "node:stream/promises";

export const ROOT = "/var/backups/ianep";
export const EXPORT_TTL_MS = 60 * 60 * 1000;
export const PACKAGE_FILES = ["database.dump", "storage.tar.gz", "SHA256SUMS", "manifest.json"] as const;
export const DOWNLOAD_HEADERS = { "Content-Type": "application/gzip", "Content-Disposition": "attachment; filename=ianep-backup.tar.gz", "Cache-Control": "private, no-store, max-age=0", "X-Content-Type-Options": "nosniff" } as const;
export function parseMode(value: unknown): Mode | null { return value === "server" || value === "download" ? value : null; }
const NAME = /^\d{8}T\d{6}Z-[0-9a-f]{8}$/;
const ID = /^[0-9a-f-]{36}$/;
export type Mode = "server" | "download";
export type Status = { id: string; mode: Mode; state: "running" | "success" | "failed"; startedAt: string; finishedAt?: string; durationMs?: number; dbBytes?: number; storageBytes?: number; verified?: boolean; ownerId?: string; sessionVersion?: number; expiresAt?: string; message?: string };
const statusPath = (root: string) => join(root, "status.json");
const lockPath = (root: string) => join(root, ".running");
function inside(root: string, child: string) { const target = resolve(root, child); if (!target.startsWith(resolve(root) + sep)) throw new Error("Invalid backup path"); return target; }
async function assertRoot(root: string) { const info = await lstat(root); if (!info.isDirectory()) throw new Error("Invalid backup root"); }
export async function backupAvailable(root = ROOT) { try { await assertRoot(root); await access(root, constants.R_OK | constants.W_OK | constants.X_OK); return true; } catch { return false; } }
async function exportsRoot(root: string) { const path = join(root, "exports"); const info = await lstat(path).catch(() => null); if (info && !info.isDirectory()) throw new Error("Invalid export root"); return path; }
async function safeDirectory(root: string, name: string) { if (!NAME.test(name)) throw new Error("Invalid backup name"); const path = inside(root, name); if (!(await lstat(path)).isDirectory()) throw new Error("Invalid backup directory"); return path; }
async function run(command: string, args: string[], env?: NodeJS.ProcessEnv, output?: string) { await new Promise<void>((ok, fail) => { const child = spawn(command, args, { env, stdio: ["ignore", output ? "pipe" : "ignore", "ignore"] }); let file: ReturnType<typeof createWriteStream> | undefined; if (output && child.stdout) { file = createWriteStream(output, { mode: 0o600 }); child.stdout.pipe(file); file.on("error", fail); } child.on("error", fail); child.on("close", code => code === 0 ? ok() : fail(new Error(`${command} failed`))); }); }
async function digest(path: string) { const hash = createHash("sha256"); await pipeline(createReadStream(path), hash); return hash.digest("hex"); }
async function atomicJson(path: string, value: unknown) { const temp = `${path}.${randomUUID()}.tmp`; await writeFile(temp, JSON.stringify(value), { mode: 0o600 }); await rename(temp, path); }
export async function readStatus(root = ROOT): Promise<Status | null> { try { return JSON.parse(await readFile(statusPath(root), "utf8")) as Status; } catch { return null; } }
export async function successfulSets(root = ROOT) { await assertRoot(root).catch(error => { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; }); const entries = await readdir(root, { withFileTypes: true }).catch(() => []); const result: { name: string; createdAt: number }[] = []; for (const entry of entries) { if (!entry.isDirectory() || !NAME.test(entry.name)) continue; const path = await safeDirectory(root, entry.name); try { const data = JSON.parse(await readFile(join(path, "manifest.json"), "utf8")); if (data.state !== "success" || data.name !== entry.name || data.verified !== true || !Number.isFinite(Date.parse(data.createdAt)) || !entry.name.startsWith(new Date(data.createdAt).toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z"))) continue; result.push({ name: entry.name, createdAt: Date.parse(data.createdAt) }); } catch { /* incomplete sets are never eligible */ } } return result.sort((a,b) => b.createdAt - a.createdAt || b.name.localeCompare(a.name)); }
export async function pruneSuccessful(root = ROOT) { await assertRoot(root); const sets = await successfulSets(root); for (const item of sets.slice(2)) { const path = await safeDirectory(root, item.name); await rm(path, { recursive: true, force: false }); } return sets.slice(0, 2).map(x => x.name); }
export async function cleanupExports(root = ROOT, now = Date.now()) { const dir = await exportsRoot(root); const entries = await readdir(dir, { withFileTypes: true }).catch(() => []); for (const entry of entries) { if (!entry.isDirectory() || !ID.test(entry.name)) continue; const path = inside(dir, entry.name); const info = await lstat(path); if (!info.isDirectory()) continue; const expires = await readFile(join(path, "job.json"), "utf8").then(x => Date.parse(JSON.parse(x).expiresAt)).catch(() => 0); if (expires < now) { const active = await readStatus(root); const lock = await lstat(lockPath(root)).catch(() => null); if (lock?.isDirectory() && active?.state === "running" && active.id === entry.name) continue; await rm(path, { recursive: true, force: true }); } } }
export async function claim(root: string, mode: Mode, ownerId?: string, sessionVersion?: number) { await mkdir(root, { recursive: true, mode: 0o700 }); await assertRoot(root); await chmod(root, 0o700); await cleanupExports(root); const id = randomUUID(); const status: Status = { id, mode, state: "running", startedAt: new Date().toISOString(), ownerId, sessionVersion }; try { await mkdir(lockPath(root), { mode: 0o700 }); } catch { throw new Error("BACKUP_BUSY"); } try { await atomicJson(statusPath(root), status); if (mode === "download") { const exports = await exportsRoot(root); const dir = inside(exports, id); await mkdir(dir, { recursive: true, mode: 0o700 }); await atomicJson(join(dir, "job.json"), { ownerId, sessionVersion, expiresAt: new Date(Date.now() + EXPORT_TTL_MS).toISOString(), state: "running" }); } return status; } catch (error) { await rm(lockPath(root), { recursive: true, force: true }); throw error; } }
export async function packageExport(dir: string) { await run("tar", ["-czf", join(dir, "ianep-backup.tar.gz"), "-C", dir, ...PACKAGE_FILES]); }
export async function execute(root: string, status: Status, dbUrl: string, storageDir: string) { const started = Date.now(); let dir = ""; try { const db = new URL(dbUrl); if (!/^postgres(?:ql)?:$/.test(db.protocol) || !storageDir.startsWith("/") || resolve(storageDir) === "/") throw new Error("Invalid backup configuration"); const stamp = new Date(status.startedAt).toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z"); const name = `${stamp}-${status.id.slice(0,8)}`; dir = status.mode === "server" ? inside(root, name) : inside(join(root, "exports"), status.id); await mkdir(dir, { recursive: status.mode === "download", mode: 0o700 }); const dump = join(dir, "database.dump"), storage = join(dir, "storage.tar.gz"); const pgEnv: NodeJS.ProcessEnv = { ...process.env, PGHOST: db.hostname, PGPORT: db.port || "5432", PGUSER: decodeURIComponent(db.username), PGPASSWORD: decodeURIComponent(db.password), PGDATABASE: db.pathname.slice(1), PGSSLMODE: db.searchParams.get("sslmode") || "prefer" }; delete pgEnv.DATABASE_URL; await run("pg_dump", ["-Fc", "-f", dump], pgEnv); const storageParent = resolve(storageDir, ".."); const storageName = resolve(storageDir).slice(storageParent.length + 1); await run("tar", ["-czf", storage, "-C", storageParent, storageName]); await run("pg_restore", ["--list", dump]); await run("tar", ["-tzf", storage]); const dbHash = await digest(dump), storageHash = await digest(storage); await writeFile(join(dir, "SHA256SUMS"), `${dbHash}  database.dump\n${storageHash}  storage.tar.gz\n`, { mode: 0o600 }); if (await digest(dump) !== dbHash || await digest(storage) !== storageHash) throw new Error("Checksum mismatch"); const dbBytes = (await stat(dump)).size, storageBytes = (await stat(storage)).size; const manifest = { name, state: "success", createdAt: status.startedAt, verified: true, dbBytes, storageBytes, durationMs: Date.now()-started, dbSha256: dbHash, storageSha256: storageHash }; await atomicJson(join(dir, "manifest.json"), manifest); if (status.mode === "download") { await packageExport(dir); await atomicJson(join(dir, "job.json"), { ownerId: status.ownerId, sessionVersion: status.sessionVersion, expiresAt: new Date(Date.now() + EXPORT_TTL_MS).toISOString(), state: "ready" }); } const done: Status = { ...status, state: "success", finishedAt: new Date().toISOString(), durationMs: Date.now()-started, dbBytes, storageBytes, verified: true, expiresAt: status.mode === "download" ? new Date(Date.now()+EXPORT_TTL_MS).toISOString() : undefined }; await atomicJson(statusPath(root), done); if (status.mode === "server") await pruneSuccessful(root); } catch { await atomicJson(statusPath(root), { ...status, state: "failed", finishedAt: new Date().toISOString(), durationMs: Date.now()-started, message: "Не удалось создать или проверить резервную копию." }); if (status.mode === "download" && dir) await rm(dir, { recursive: true, force: true }); } finally { await rm(lockPath(root), { recursive: true, force: true }); } }
export async function getDownload(root: string, id: string, ownerId: string, sessionVersion: number) { if (!ID.test(id)) return null; const dir = inside(await exportsRoot(root), id); const info = await readFile(join(dir, "job.json"), "utf8").then(x => JSON.parse(x)).catch(() => null); if (!info || info.ownerId !== ownerId || info.sessionVersion !== sessionVersion || info.state !== "ready" || Date.parse(info.expiresAt) <= Date.now()) return null; const path = join(dir, "ianep-backup.tar.gz"); if (!(await lstat(path).catch(() => null))?.isFile()) return null; return { path, dir, size: (await stat(path)).size }; }

export async function latestSuccessfulDetails(root = ROOT) { const first = (await successfulSets(root))[0]; if (!first) return null; const path = await safeDirectory(root, first.name); const data = JSON.parse(await readFile(join(path, "manifest.json"), "utf8")); return { createdAt: data.createdAt as string, dbBytes: data.dbBytes as number, storageBytes: data.storageBytes as number, durationMs: data.durationMs as number, verified: data.verified as boolean }; }

export async function authorizedDownload(root: string, id: string, session: { adminId: string; sessionVersion: number } | null) { if (!session) return null; return getDownload(root, id, session.adminId, session.sessionVersion); }

export async function readyDownload(root: string, session: { adminId: string; sessionVersion: number }) { const dir = await exportsRoot(root); const entries = await readdir(dir, { withFileTypes: true }).catch(() => []); for (const entry of entries.reverse()) { if (!entry.isDirectory() || !ID.test(entry.name)) continue; const item = await authorizedDownload(root, entry.name, session); if (item) return entry.name; } return null; }
