
import { Select } from "@/components/ui/fields/Select";
import { DateField } from "@/components/ui/fields/DateField";
import Link from "next/link";
import type { ProjectDetail } from "@/server/client/service";
import { dateLabel, timeLabel, kinds, statuses, paymentStatuses, warrantyEnd } from "@/server/client/model";
import { adminProjectAction, clientDecision, addMaterial } from "@/app/client/actions";
import { WorkspaceForm, MaterialFields, ImagePreview } from "./forms";
import s from "./workspace.module.css";

type Material = { fileId?: string | null; id: string; title: string; url: string; kind: keyof typeof kinds; file?: { physicalDeletedAt: Date | null } | null };
function Materials({ materials }: { materials: Material[] }) {
  return <div className={s.grid}>{materials.map(material => <div key={material.id} className={s.material}>{material.file?.physicalDeletedAt ? <><strong>{material.title}</strong><span className={s.muted}>Физический файл очищен по сроку хранения. Метаданные версии и согласования сохранены.</span></> : <>{material.kind === "IMAGE" && <ImagePreview url={material.url} title={material.title} />}<a href={material.url} target="_blank" rel="noopener noreferrer">{material.title} ↗</a><span className={s.muted}>{kinds[material.kind]} · {material.fileId && material.kind !== "IMAGE" ? "скачивание файла" : "открывается в новой вкладке"}</span></>}</div>)}</div>;
}
function PaymentFields({ payment }: { payment?: ProjectDetail["payments"][number] }) {
  return <>{payment && <input type="hidden" name="paymentId" value={payment.id} />}<label>Назначение / этап<input name="title" defaultValue={payment?.title} required maxLength={200} /></label><label>Сумма, ₽<input name="amount" inputMode="decimal" type="number" step="0.01" min="0.01" max="9999999999.99" defaultValue={payment?.amount.toString()} required /></label><label>Статус<Select name="status" defaultValue={payment?.status ?? "PLANNED"}>{Object.entries(paymentStatuses).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></label><div className={s.grid}><DateField label="Срок оплаты" name="dueAt" defaultValue={payment?.dueAt?.toISOString().slice(0, 10)} /><DateField label="Дата оплаты" name="paidAt" defaultValue={payment?.paidAt?.toISOString().slice(0, 10)} /></div><label>Ссылка на документ<input type="url" name="documentUrl" defaultValue={payment?.documentUrl ?? ""} maxLength={2000} /></label></>;
}
const projectTabs = ["overview", "stages", "approvals", "materials", "payments", "history", "access"] as const;
type ProjectTab = (typeof projectTabs)[number];

export function ProjectWorkspace({ project, admin = false, tab: requestedTab, stageId, retentionDefault = 365 }: { project: ProjectDetail; admin?: boolean; tab?: string; stageId?: string; retentionDefault?: number }) {
  const action = (command: string) => adminProjectAction.bind(null, project.id, command);
  const archived = Boolean(project.archivedAt);
  const tab: ProjectTab = projectTabs.includes(requestedTab as ProjectTab) && (admin || requestedTab !== "access") ? requestedTab as ProjectTab : "overview";
  const stages = project.stages.filter(stage => !stage.archivedAt);
  const pending = stages.filter(stage => stage.status === "IN_REVIEW");
  const active = stages.find(stage => !["COMPLETED", "WARRANTY"].includes(stage.status));
  const selectedStage = stages.find(stage => stage.id === stageId) ?? pending[0] ?? active ?? stages[0];
  const root = admin ? "/admin/projects" : "/client";
  return <div className={s.stack}><div className={s.row}><Link href={root}>← Все проекты</Link>{admin && project.brief && <Link href={`/admin/briefs/${project.brief.id}`}>Заявка № {project.brief.number} →</Link>}</div><div className={s.intro}><p className={s.muted}>{admin ? project.client.name : "Ваш проект"}</p><div className={s.row}><h1>{project.title}</h1><span className={s.badge}>{archived ? "В архиве" : statuses[project.status]}</span></div><p className={s.muted}>{project.description}</p></div>
    {tab === "overview" && (archived && admin ? <section className={s.archivePanel}><h2>Проект находится в архиве</h2><p>Клиент больше не видит проект в личном кабинете. История, материалы и платежи доступны здесь только для просмотра.</p><p className={s.muted}>{project.deleteAfter ? `Автоматическое удаление запланировано на ${dateLabel(project.deleteAfter)}.` : "Автоматическое удаление отключено."}</p><WorkspaceForm action={action("restore-project")} submit="Восстановить проект"><p className={s.muted}>После восстановления проект снова появится у клиента.</p></WorkspaceForm></section> : <section className={s.focus}><h2>{pending.length ? (admin ? "Ожидаем решение клиента" : "Требуется от вас") : "Что происходит сейчас"}</h2>{pending.length ? pending.map(stage => <div className={s.row} key={stage.id}><p>{stage.title}</p><a href={`?tab=approvals&stage=${stage.id}`}>{admin ? "Ожидаем решение клиента" : "Проверить результат →"}</a></div>) : <p>{active ? `${active.title} · ${statuses[active.status]}` : stages.length ? "Все этапы завершены." : "Готовим этапы проекта."}</p>}<p>Далее: {project.nextAction || "IANep уточнит следующий шаг."}</p></section>)}
    <nav className={s.projectNav} aria-label="Разделы проекта"><Link className={tab === "overview" ? s.projectNavActive : ""} href="?tab=overview">Обзор</Link><Link className={tab === "stages" ? s.projectNavActive : ""} href="?tab=stages">Этапы</Link><Link className={tab === "approvals" ? s.projectNavActive : ""} href={selectedStage ? `?tab=approvals&stage=${selectedStage.id}` : "?tab=approvals"}>Согласования</Link><Link className={tab === "materials" ? s.projectNavActive : ""} href="?tab=materials">Материалы</Link><Link className={tab === "payments" ? s.projectNavActive : ""} href="?tab=payments">Оплата</Link><Link className={tab === "history" ? s.projectNavActive : ""} href="?tab=history">История</Link>{admin && <Link className={tab === "access" ? s.projectNavActive : ""} href="?tab=access">Доступ клиента</Link>}</nav>
    {tab === "approvals" && stages.length > 0 && <nav className={s.stageNav} aria-label="Этапы проекта">{stages.map((stage, index) => <Link key={stage.id} className={selectedStage?.id === stage.id ? s.stageNavActive : ""} href={`?tab=approvals&stage=${stage.id}`} aria-current={selectedStage?.id === stage.id ? "page" : undefined}><span>{index + 1}</span>{stage.title}<small>{statuses[stage.status]}</small></Link>)}</nav>}
    {tab === "overview" && admin && !archived && <><details className={s.panel}><summary>Настройки проекта и следующий шаг</summary><WorkspaceForm action={action("project")}><label>Название<input name="title" defaultValue={project.title} required maxLength={200} /></label><label>Описание<textarea name="description" defaultValue={project.description} maxLength={10000} /></label><label>Что будет дальше<textarea name="nextAction" defaultValue={project.nextAction} maxLength={10000} /></label><label>Состояние проекта<Select name="status" defaultValue={project.status}>{(["PREPARATION", "IN_PROGRESS", "COMPLETED", "WARRANTY"] as const).map(status => <option value={status} key={status}>{statuses[status]}</option>)}</Select></label><DateField label="Дата запуска" name="launchedAt" defaultValue={project.launchedAt?.toISOString().slice(0, 10)} /></WorkspaceForm></details><details className={s.panel}><summary>Перенести проект в архив</summary><WorkspaceForm action={action("archive-project")} submit="Перенести в архив" tone="danger"><label>Срок хранения<Select name="retention" defaultValue={String(retentionDefault)}>{Array.from(new Set([retentionDefault, 30, 90, 180, 365, 730])).sort((a,b) => a-b).map(days => <option value={days} key={days}>{days === retentionDefault ? `${days} дней · системный срок` : `${days} дней`}</option>)}<option value="forever">Хранить без срока очистки</option></Select></label><p className={s.muted}>Проект исчезнет из кабинета клиента. После срока он станет кандидатом на ручную очистку; история автоматически не удаляется.</p></WorkspaceForm></details></>}
    {tab === "stages" && <section className={s.panel} id="roadmap"><h2>План проекта</h2>{stages.length ? <ol className={s.roadmap}>{stages.map((stage, index) => <li key={stage.id}><span className={s.number}>{index + 1}</span><div className={s.row}><a href={`?tab=approvals&stage=${stage.id}`}>{stage.title}</a><span className={`${s.badge} ${stage.status === "IN_REVIEW" ? s.review : ""}`}>{statuses[stage.status]}</span></div></li>)}</ol> : <p className={s.muted}>Этапы появятся после подготовки плана.</p>}{admin && !archived && <WorkspaceForm action={action("add-stage")} submit="Добавить этап"><label>Название нового этапа<input name="title" required maxLength={200} /></label></WorkspaceForm>}</section>}
    {tab === "approvals" && <section id="approvals" className={s.stack}><h2>Результаты и согласования</h2>{!stages.length && <p className={s.muted}>Здесь будут опубликованные результаты этапов.</p>}{selectedStage ? [selectedStage].map(stage => {
      const rounds = stage.versions.filter(version => version.decision?.kind === "CHANGES" && version.decision.countsTowardLimit).length;
      return <article key={stage.id} id={`stage-${stage.id}`} className={`${s.panel} ${s.stack}`}><div className={s.row}><h3>{stage.title}{stage.archivedAt ? " · убран из плана" : ""}</h3><span className={s.badge}>{statuses[stage.status]}</span></div><p className={s.muted}>{stage.description}</p><p className={s.muted}>Клиентские раунды правок: {rounds} из {stage.includedRounds} включённых.{rounds >= stage.includedRounds ? " Дальнейший объём согласуем с IANep; отправка правок доступна." : ""} Исправления ошибок IANep могут быть исключены из счётчика.</p>
        {admin && !archived && !stage.archivedAt && <details><summary>Управлять этапом</summary><WorkspaceForm action={action("stage")}><input type="hidden" name="stageId" value={stage.id} /><label>Название<input name="title" defaultValue={stage.title} required maxLength={200} /></label><label>Описание<textarea name="description" defaultValue={stage.description} maxLength={10000} /></label><label>Статус<Select name="status" defaultValue={stage.status}>{Object.entries(statuses).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></label><p className={s.muted}>Статус «На согласовании» выставляется при публикации. Принятие и правки — при решении клиента.</p><label>Действие<Select name="operation"><option value="save">Сохранить поля</option><option value="up">Поднять в плане</option><option value="down">Опустить в плане</option><option value="archive">Удалить из плана, сохранить историю</option></Select></label></WorkspaceForm></details>}
        {admin && !archived && !stage.archivedAt && (!stage.versions[0] || stage.versions[0].decision) && <details><summary>Опубликовать новую версию результата</summary><WorkspaceForm action={action("publish")} submit="Опубликовать на согласование"><input type="hidden" name="stageId" value={stage.id} /><label>Комментарий IANep<textarea name="comment" required maxLength={10000} placeholder="Что готово и что нужно проверить клиенту" /></label><MaterialFields multiple projectId={project.id} side="ADMIN" /><p className={s.muted}>После публикации состав версии и комментарий не редактируются. Проверьте доступ клиента к ссылкам. Загруженные файлы сохраняются без перезаписи. Содержимое внешних ссылок может изменяться у их владельца.</p></WorkspaceForm></details>}
        {!stage.versions.length && <p className={s.muted}>Результат пока не опубликован.</p>}
        {stage.versions.map((version, index) => <div key={version.id} className={s.version}><div className={s.row}><h3>Версия {version.number}{index === 0 ? " · последняя" : ""}</h3><time className={s.muted}>{timeLabel(version.publishedAt)}</time></div><p>{version.comment}</p><Materials materials={version.materials} />
          {version.decision ? <div className={s.notice}><strong>{version.decision.kind === "ACCEPTED" ? "Клиент принял этап" : "Клиент отправил правки"}</strong><p className={s.muted}>{timeLabel(version.decision.createdAt)} · версия {version.number}</p>{version.decision.changes && <p>{version.decision.changes}</p>}{version.decision.kind === "CHANGES" && <p className={s.muted}>{version.decision.countsTowardLimit ? "Учитывается в лимите клиентских правок" : "Не учитывается в лимите"}{version.decision.exceptionReason ? `: ${version.decision.exceptionReason}` : ""}</p>}</div> : <p className={s.muted}>Ожидает решения клиента</p>}
          {!admin && !archived && !stage.archivedAt && index === 0 && !version.decision && stage.status === "IN_REVIEW" && <WorkspaceForm action={clientDecision.bind(null, project.id)} submit="Отправить решение"><input type="hidden" name="versionId" value={version.id} /><label>Ваше решение<Select name="kind" label="Ваше решение" defaultValue="" required><option value="" disabled>Выберите решение</option><option value="ACCEPTED">Принять этап</option><option value="CHANGES">Отправить правки</option></Select></label><label>Консолидированный список правок<textarea name="changes" maxLength={10000} placeholder="1. Что нужно изменить и где…&#10;2. Какой результат ожидаете…" /></label><p className={s.muted}>Для правок заполните один полный список. При принятии текст правок не сохраняется. Решение будет привязано к версии {version.number} и сохранено в истории.</p></WorkspaceForm>}
          {admin && !archived && version.decision?.kind === "CHANGES" && <details><summary>Учёт раунда / исправление ошибки IANep</summary><WorkspaceForm action={action("exception")}><input type="hidden" name="decisionId" value={version.decision.id} /><label>Учёт в лимите<Select name="counts" defaultValue={version.decision.countsTowardLimit ? "yes" : "no"}><option value="yes">Клиентский раунд — учитывать</option><option value="no">Ошибка IANep / исключение — не учитывать</option></Select></label><label>Причина<textarea name="reason" required defaultValue={version.decision.exceptionReason ?? ""} maxLength={10000} /></label></WorkspaceForm></details>}
        </div>)}
      </article>;
    }) : null}</section>}
    {tab === "materials" && <section id="materials" className={`${s.panel} ${s.stack}`}><h2>Материалы проекта</h2><p className={s.muted}>Материалы результатов находятся в версиях выше. Здесь — общие файлы и ссылки обеих сторон.</p>{project.materials.map(material => <div key={material.id} className={s.version}><Materials materials={[material]} /><p className={s.muted}>{material.authorSide === "ADMIN" ? "IANep" : "Клиент"} · {timeLabel(material.createdAt)} · {material.stageId ? project.stages.find(stage => stage.id === material.stageId)?.title : "Весь проект"}</p></div>)}{!project.materials.length && <p className={s.muted}>Общих материалов пока нет.</p>}{!archived && <details><summary>Добавить материал</summary><WorkspaceForm action={addMaterial.bind(null, project.id, admin ? "ADMIN" : "CLIENT")} submit="Добавить материал"><label>Относится к<Select name="stageId"><option value="">Всему проекту</option>{stages.map(stage => <option value={stage.id} key={stage.id}>{stage.title}</option>)}</Select></label><MaterialFields projectId={project.id} side={admin ? "ADMIN" : "CLIENT"} />{admin && <label className={s.checkbox}><input type="checkbox" name="notify" value="yes" />Это важный материал — уведомить клиента</label>}</WorkspaceForm></details>}</section>}
    {tab === "payments" && <section id="payments" className={`${s.panel} ${s.stack}`}><h2>Оплата</h2><p className={s.muted}>Оплата по согласованным реквизитам. Статус подтверждает IANep.</p>{project.payments.length ? project.payments.map(payment => <article key={payment.id} className={s.version}><div className={s.row}><h3>{payment.title}</h3><strong>{new Intl.NumberFormat("ru-RU", { style: "currency", currency: "RUB" }).format(Number(payment.amount))}</strong></div><p>{paymentStatuses[payment.status]} · Срок: {dateLabel(payment.dueAt)}{payment.paidAt ? ` · Оплачено: ${dateLabel(payment.paidAt)}` : ""}</p>{payment.documentUrl && <a href={payment.documentUrl} target="_blank" rel="noopener noreferrer">Документ к платежу ↗</a>}{admin && !archived && <details><summary>Изменить платёж</summary><WorkspaceForm action={action("payment")}><PaymentFields payment={payment} /></WorkspaceForm></details>}</article>) : <p className={s.muted}>График платежей пока не добавлен.</p>}{admin && !archived && <details><summary>Добавить платёж</summary><WorkspaceForm action={action("payment")} submit="Добавить платёж"><PaymentFields /></WorkspaceForm></details>}</section>}
    {tab === "overview" && <section className={s.panel}><h2>Запуск и гарантия</h2><p>{project.launchedAt ? `Запуск: ${dateLabel(project.launchedAt)}. Гарантия до ${dateLabel(warrantyEnd(project.launchedAt, project.warrantyDays))}.` : "Дата запуска будет указана после завершения проекта."}</p><p className={s.muted}>30 календарных дней на исправление собственных ошибок IANep в согласованном объёме. Новые функции, изменения поведения и контента, сторонние сервисы, хостинг и окружение клиента не входят в гарантию.</p></section>}
    {admin && tab === "access" && <div className={s.accessGrid}><section className={`${s.panel} ${s.stack}`}><div><h2>Данные для входа</h2><p className={s.muted}>Текущий логин виден администратору. Пароль хранится необратимо, поэтому его можно только заменить.</p><p className={s.credentialLine}>Текущий логин: <strong>{project.client.username}</strong></p></div><WorkspaceForm action={action("client-access")} submit="Сохранить данные"><label>Имя клиента<input name="name" defaultValue={project.client.name} required maxLength={200} /></label><label>Новый логин<input name="username" minLength={3} maxLength={100} autoComplete="off" placeholder="Оставьте пустым, чтобы не менять" pattern="[a-zA-Z0-9._@+\-]{3,100}" /></label><label>Новый пароль<input name="password" type="password" minLength={12} maxLength={200} autoComplete="new-password" placeholder="Оставьте пустым, чтобы не менять" /></label><p className={s.muted}>Если задать новый пароль, все ранее открытые сессии клиента завершатся.</p></WorkspaceForm></section><section className={`${s.panel} ${s.stack}`}><div><h2>Активные сессии</h2><p className={s.muted}>Завершите доступ на всех устройствах, если данные входа могли попасть к постороннему.</p></div><WorkspaceForm action={action("reset-client-sessions")} submit="Завершить все сессии" tone="danger"><p>Клиенту потребуется снова войти с действующим логином и паролем.</p></WorkspaceForm></section></div>}
    {tab === "history" && <section id="events" className={`${s.panel} ${s.stack}`}><h2>История событий</h2><p className={s.muted}>События сохранены в кабинете. Email и телефонная доставка не подключены.</p><div className={s.history}>{project.events.map(event => <article key={event.id}><p>{event.message}</p><p className={s.muted}>{timeLabel(event.createdAt)} · {event.actorSide === "ADMIN" ? "IANep" : "Клиент"} · Кабинет: сохранено</p></article>)}</div></section>}
  </div>;
}
