import Image from "next/image";
import Link from "next/link";
import { redirect } from "next/navigation";
import { ThemeToggle } from "@/components/layout/ThemeToggle";
import { getClientSession } from "@/server/client/auth";
import { ClientLoginForm } from "./login-form";
import styles from "@/app/admin/admin.module.css";
export const metadata = { title: "Вход в кабинет клиента" };
export default async function ClientLogin() {
  if (await getClientSession()) redirect("/client");
  return <main id="main-content" className={styles.loginMain}><header className={styles.loginHeader}><Link href="/" className={styles.brandName}>IANep</Link><ThemeToggle /></header><div className={styles.loginLayout}><section className={styles.loginVisual} aria-label="Рабочее пространство клиента"><div className={styles.visualCaption}><span className={styles.accessLabel}><span /> Кабинет клиента</span><h2>Проект движется.<br />Вы видите главное.</h2><p>Результаты, согласования и следующие действия собраны в одном месте.</p></div><div className={styles.mascotStage}><div className={styles.orbit} aria-hidden="true" /><div className={styles.mascotFigure}><Image src="/images/admin/mascot-access-v1.png" alt="Фирменный робот IANep приглашает войти в кабинет клиента" width={1254} height={1254} sizes="(max-width: 760px) 58vw, 420px" preload className={styles.loginMascot} /><svg className={styles.mascotEyes} viewBox="0 0 1254 1254" fill="none" aria-hidden="true"><g className={styles.eyeBlink}><rect x="553" y="406" width="38" height="62" rx="19" /><rect x="701" y="417" width="38" height="62" rx="19" /></g></svg></div><span className={styles.accessCard} aria-hidden="true">IANep client <span>↗</span></span></div><span className={styles.visualFooter}>Всё по проекту доступно после входа.</span></section><section className={styles.loginCard} aria-labelledby="client-login-title"><p className={styles.eyebrow}>Личный кабинет</p><h1 id="client-login-title" className={styles.loginTitle}>Войти в проект</h1><p className={styles.loginHint}>Используйте логин и пароль, которые вы получили от IANep.</p><ClientLoginForm /><p className={styles.loginNote}>Если данные для входа не подходят, свяжитесь с вашим менеджером.</p><Link className={styles.loginBack} href="/">← Вернуться на сайт</Link></section></div><footer className={styles.loginFooter}><span>IANep / Кабинет клиента</span><span>Доступ только по приглашению</span></footer></main>;
}
